### PR TITLE
chore: improve import

### PR DESCRIPTION
**Pull request by recca0120**

### CODE REVIEW

**Review by nzbin — COMMENTED** [review]
I am wondering why the `package-lock.json` is always be updated?

**Comment by recca0120** [comment]
https://docs.npmjs.com/cli/v8/commands/npm-ci

Because I use npm i to install packages, it will update package-lock.json, next time I will try to install package use npm ci, maybe can keep package-lock.json.

**Comment by recca0120** [comment]
This time I can use git rebase to restore package-lock.json before merge this pr

**Comment by nzbin** [comment]
> https://docs.npmjs.com/cli/v8/commands/npm-ci
> 
> Because I use npm i to install packages, it will update package-lock.json, next time I will try to install package use npm ci, maybe can keep package-lock.json.

The npm i maybe incorrect, there has many keys as following. When I run npm i, these keys will be deleted.

```
"node_modules/@ampproject/remapping": {
...
},
"node_modules/@angular-devkit/architect": {
...
},
"node_modules/@angular-devkit/build-angular": {
...
}
...
```

**Review by nzbin — APPROVED** [review]

**Comment by recca0120** [comment]
截圖 2021-11-22 下午1 28 29

I find lockfileVersion is not the same when I check package-lock.json
my npm version is 7, maybe your npm version is 5 or 6
when npm version is different, use npm I package-lock.json will be changed
but use npm ci package-lock.json wont be changed.

**Pull request merged**
