### PR TITLE
Load menu when user changed

### PR DESCRIPTION
**Pull request by recca0120**

### CODE REVIEW

**Review by nzbin — COMMENTED** [review]
It is unnecessary to use an oberver instead of a complete callback.
Please check this issue https://github.com/microsoft/TypeScript/issues/43053

**Review by nzbin — COMMENTED** [review]
This project use Prettier to format codes, you can add Prettier plugin on VSCode.

**Comment by recca0120** [comment]
ok, add prettier to pre-commit

**Review by nzbin — COMMENTED** [review]
Just use Prettier for `.ts` files, the `.html` formatting is inappropriate.

**Comment by recca0120** [comment]
done

**Comment by recca0120** [comment]
do I need to remove oberver?

**Comment by nzbin** [comment]
Many thanks!

**Pull request merged**
